name: Lint

on:
  push:
    paths-ignore:
      - 'README.rst'
      - '.gitignore'
      - '.dockerignore'
      - 'Dockerfile'


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          src: "./src"
